### PR TITLE
Handle stacks from internal exceptions sometimes thrown by Firefox (fixes #49)

### LINKED ISSUE #49: Handle frames generated by Firefox internal errors (e.g. NS_ERROR_FAILURE)
It's possible to get Firefox to generate errors that bubble up from its internals. They can generate bizarre stack trace formats that are not currently handled by TraceKit.

More here: https://developer.mozilla.org/en-US/docs/Mozilla/Errors

Example `error.stack` from such an error, generated by `try/catch` around w/ `XMLHttpRequest.prototype.send` that fails in a specific situation:

```
[2]</Raven.prototype._wrapBuiltIns/</<@http://127.0.0.1:8002/dist/raven.js:703:28
App.prototype.foo@file:///Users/benvinegar/Projects/sentry/index.html:15:2
bar@file:///Users/benvinegar/Projects/sentry/index.html:20:3
@file:///Users/benvinegar/Projects/sentry/index.html:23:1
```

TraceKit parses the first frame into:

```javascript
{
  url: "[2]</Raven.prototype._wrapBuiltIns/</<@http://127.0.0.1:8002/dist/raven.js",
  func: "?",
  args: [],
  line: 703,
  column: 28
}
```

More info on how I generated this error in getsentry/raven-js#528

### PR DESCRIPTION
**Pull request by benvinegar**

### CODE REVIEW

File: tracekit.js [hunk 1]
```diff
@@ -697,7 +697,7 @@ TraceKit.computeStackTrace = (function computeStackTraceWrapper() {
         }
 
         var chrome = /^\s*at (.*?) ?\(((?:file|https?|blob|chrome-extension|native|eval).*?)(?::(\d+))?(?::(\d+))?\)?\s*$/i,
-            gecko = /^\s*(.*?)(?:\((.*?)\))?(?:^|@)((?:file|https?|blob|chrome|\[).*?)(?::(\d+))?(?::(\d+))?\s*$/i,
+            gecko = /^\s*(.*?)(?:\((.*?)\))?(?:^|@)((?:file|https?|blob|chrome|\[native).*?)(?::(\d+))?(?::(\d+))?\s*$/i,
```
Comment (benvinegar) [inline tracekit.js]: @niemyjski – Was the `\[` match here intended to match on anything besides `[native code]`?

**Comment by benvinegar** [comment]
@niemyjski – any news on this?

File: tracekit.js (hunk 1 above)
Comment (niemyjski) [inline tracekit.js]: Yes, some engines will have native or native code in the stack trace. I'm worried that this could be localized. What are your thoughts?

**Comment by niemyjski** [comment]
@benvinegar Sorry for the late reply. I just left a comment to your reply. Other than that it looks good and I'll merge if you have no other feedback to my comment.

File: tracekit.js (hunk 1 above)
Comment (benvinegar) [inline tracekit.js]: > I'm worried that this could be localized. 

Searching through the [Firefox source code](https://dxr.mozilla.org/mozilla-central/search?q=%5Bnative&redirect=true&case=false), I don't think this string is localized.

Just to be sure, I also downloaded the [French edition of Firefox](https://www.mozilla.org/en-US/firefox/all/) and verified that the string is the same:

image

**Comment by niemyjski** [comment]
Thanks for your help! Do you need me to release a new version?

**Comment by benvinegar** [comment]
> Do you need me to release a new version?

Doesn't matter to us, since we maintain a pretty diverged fork of TraceKit vendored inside [getsentry/raven-js](https://github.com/getsentry/raven-js).

**Comment by niemyjski** [comment]
@benvinegar still would like to work with you and get you onto the main fork. If you'd like to meet up or talk on skype / gitter feel free to reach out to me.
